// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: syiqvwvzgutyeoymoxuf

class SupabaseConfig {
  static const String supabaseUrl = 'https://syiqvwvzgutyeoymoxuf.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aXF2d3Z6Z3V0eWVveW1veHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNTAzMjYsImV4cCI6MjA3NzgyNjMyNn0.qyq4t0PqqK80E_ch1c5yvVma5mWvu7nzgV2yoxIsxIQ';
}
